project:
  type: website

website:
  title: "AMAP Lab - Resources for good programming practices"
  search: true
  navbar:
    left:
      - href: src/index.qmd
        text: "![](/src/logo_amap1.jpg){width=15%}"
      - src/starting_project.qmd
      - src/documentation.qmd
      - src/git.qmd
      - src/ci_cd.qmd
      - src/testing.qmd
      - src/hpc.qmd
      - src/about.qmd
      - src/resources.qmd
  margin-footer: |
      ![](/src/logo_amap3.jpg){width=30%}

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



