project:
  type: website

website:
  title: "amap-dev-website"
  search: true
  navbar:
    left:
      - href: src/index.qmd
        text: Home
      - src/starting_project.qmd
      - src/documentation.qmd
      - src/git.qmd
      - src/ci_cd.qmd
      - src/testing.qmd
      - src/hpc.qmd
      - src/about.qmd
      - src/resources.qmd
  margin-header: |
      ![](/src/logo_amap3.jpg){width=40%}

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



