on:
  workflow_dispatch:
  push:
    branches:
      - deploy_on_palais

name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions:
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

###      - name: Publish to GitHub Pages (and render)
###        uses: quarto-dev/quarto-actions/publish@v2
###        with:
###          target: gh-pages
###        env:
###          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --chown=www-data:www-data
          path: ./_site/
          remote_path: /var/www/sites/polis-dev
          remote_host: palais.cirad.fr
          remote_user: amap
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

###      - name: Publish to palais.cirad.fr
###        run: |
###          echo "Publishing to palais.cirad.fr"
###          rsync -avhz -e "ssh -o StrictHostKeyChecking=no" --chown=www-data:www-data ./_site/ amap@palais.cirad.fr:/var/www/sites/polis-dev
###        env:
###          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}